# Generated by Django 5.0.2 on 2024-04-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mathes',
            new_name='Matches',
        ),
    ]
