# Generated by Django 5.0.2 on 2024-04-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_rename_mathes_matches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
