# Generated by Django 5.0.2 on 2024-04-27 05:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0003_delete_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Team A')),
            ],
        ),
        migrations.CreateModel(
            name='TeamB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Team B')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_link', models.URLField()),
                ('team_a_players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('team_b_players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.teama')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.teamb')),
            ],
        ),
    ]
