# Generated by Django 5.0.2 on 2024-04-29 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0005_remove_matches_team_a_remove_matches_team_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_a_name', models.CharField(max_length=100)),
                ('team_b_name', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('team_a_players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('team_b_players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
        ),
    ]
