# Generated by Django 5.0.2 on 2024-05-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='team_a_players',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team_b_players',
        ),
        migrations.AddField(
            model_name='matches',
            name='team_a_color',
            field=models.CharField(default='#000000', max_length=100),
        ),
        migrations.AddField(
            model_name='matches',
            name='team_b_color',
            field=models.CharField(default='#000000', max_length=100),
        ),
    ]
