# Generated by Django 5.0.2 on 2024-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_matches_team_a_players_matches_team_b_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='team_a_first_five',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='team_b_first_five',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
