# Generated by Django 5.0.2 on 2024-05-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_matches_team_a_first_five_matches_team_b_first_five'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='team_a_first_five',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team_b_first_five',
        ),
    ]
