# Generated by Django 5.0.2 on 2024-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_remove_matches_team_a_first_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
