# Generated by Django 5.0.2 on 2024-06-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_alter_matches_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='game_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
