# Generated by Django 5.0.2 on 2024-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teama_q1',
            name='id',
        ),
        migrations.AlterField(
            model_name='teama_q1',
            name='time',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
