# Generated by Django 5.0.2 on 2024-02-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_teama_delete_teama_q1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamA',
        ),
    ]
