# Generated by Django 5.0.2 on 2024-02-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamB',
            fields=[
                ('time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quater', models.CharField(max_length=50)),
                ('shot', models.CharField(max_length=50)),
                ('made', models.CharField(blank=True, max_length=50, null=True)),
                ('made_SJN', models.CharField(blank=True, max_length=50, null=True)),
                ('made_locx', models.FloatField(blank=True, null=True)),
                ('made_locy', models.FloatField(blank=True, null=True)),
                ('made_assist', models.CharField(blank=True, max_length=50, null=True)),
                ('made_shottype', models.CharField(blank=True, max_length=50, null=True)),
                ('miss', models.CharField(blank=True, max_length=50, null=True)),
                ('miss_outb', models.CharField(blank=True, max_length=50, null=True)),
                ('miss_reb', models.CharField(blank=True, max_length=50, null=True)),
                ('o_reb_SJN', models.CharField(blank=True, max_length=50, null=True)),
                ('d_reb_DJN', models.CharField(blank=True, max_length=50, null=True)),
                ('shot_foul', models.CharField(blank=True, max_length=50, null=True)),
                ('shot_foul_SJN', models.CharField(blank=True, max_length=50, null=True)),
                ('shot_foul_Slocx', models.FloatField(blank=True, null=True)),
                ('shot_foul_Slocy', models.FloatField(blank=True, null=True)),
                ('shot_foul_DJN', models.CharField(blank=True, max_length=50, null=True)),
                ('shot_foul_Dlocx', models.FloatField(blank=True, null=True)),
                ('shot_foul_Dlocy', models.FloatField(blank=True, null=True)),
                ('mwf', models.CharField(blank=True, max_length=50, null=True)),
                ('mwf_SJN', models.CharField(blank=True, max_length=50, null=True)),
                ('mwf_Slocx', models.FloatField(blank=True, null=True)),
                ('mwf_Slocy', models.FloatField(blank=True, null=True)),
                ('mwf_assist', models.CharField(blank=True, max_length=50, null=True)),
                ('mwf_shottype', models.CharField(blank=True, max_length=50, null=True)),
                ('mwf_DJN', models.CharField(blank=True, max_length=50, null=True)),
                ('mwf_Dlocx', models.FloatField(blank=True, null=True)),
                ('mwf_Dlocy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
