# Generated by Django 5.0.2 on 2024-03-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_teamc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamA',
        ),
        migrations.DeleteModel(
            name='TeamB',
        ),
        migrations.DeleteModel(
            name='TeamC',
        ),
    ]
