# Generated by Django 5.0.2 on 2024-03-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teama',
            old_name='quater',
            new_name='quarter',
        ),
    ]
