# Generated by Django 5.0.2 on 2024-03-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_rename_quater_teama_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='teama',
            name='shot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='shot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
