# Generated by Django 5.0.2 on 2024-03-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_teama_shot_teamb_shot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamb',
            old_name='quater',
            new_name='quarter',
        ),
    ]
