# Generated by Django 5.0.2 on 2024-03-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_alter_teama_game_time_alter_teamb_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teama',
            name='made_assist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teama',
            name='made_wf_assist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='made_assist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='made_wf_assist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
