# Generated by Django 5.0.2 on 2024-03-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_teama_made_assist_teama_made_wf_assist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teama',
            old_name='made_sjn',
            new_name='sjn',
        ),
        migrations.RenameField(
            model_name='teama',
            old_name='made_sloc',
            new_name='sloc',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='made_sjn',
            new_name='sjn',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='made_sloc',
            new_name='sloc',
        ),
    ]
