# Generated by Django 5.0.2 on 2024-03-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_rename_made_sjn_teama_sjn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teama',
            old_name='made_ajn',
            new_name='ajn',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='made_ajn',
            new_name='ajn',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='made_wf_ajn',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='made_wf_ajn',
        ),
    ]
