# Generated by Django 5.0.2 on 2024-03-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_rename_made_ajn_teama_ajn_rename_made_ajn_teamb_ajn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teama',
            old_name='made_assist',
            new_name='assist',
        ),
        migrations.RenameField(
            model_name='teama',
            old_name='made_wf_assist',
            new_name='djn',
        ),
        migrations.RenameField(
            model_name='teama',
            old_name='made_wf_sloc',
            new_name='dloc',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='made_assist',
            new_name='assist',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='made_wf_assist',
            new_name='djn',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='made_wf_sloc',
            new_name='dloc',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='made_wf_sjn',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_def_jn',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_def_loc',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_off_jn',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_off_loc',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_wf_djn',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_wf_dloc',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_wf_sjn',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='miss_wf_sloc',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='made_wf_sjn',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_def_jn',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_def_loc',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_off_jn',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_off_loc',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_wf_djn',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_wf_dloc',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_wf_sjn',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='miss_wf_sloc',
        ),
    ]
