# Generated by Django 5.0.2 on 2024-03-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0017_rename_made_assist_teama_assist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teama',
            name='dr_sjn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teama',
            name='dr_sloc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teama',
            name='or_sjn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teama',
            name='or_sloc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='dr_sjn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='dr_sloc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='or_sjn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='or_sloc',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
