# Generated by Django 5.0.2 on 2024-03-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0018_teama_dr_sjn_teama_dr_sloc_teama_or_sjn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teama',
            old_name='dr_sjn',
            new_name='dr_jn',
        ),
        migrations.RenameField(
            model_name='teama',
            old_name='dr_sloc',
            new_name='dr_loc',
        ),
        migrations.RenameField(
            model_name='teama',
            old_name='or_sjn',
            new_name='or_jn',
        ),
        migrations.RenameField(
            model_name='teama',
            old_name='or_sloc',
            new_name='or_loc',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='dr_sjn',
            new_name='dr_jn',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='dr_sloc',
            new_name='dr_loc',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='or_sjn',
            new_name='or_jn',
        ),
        migrations.RenameField(
            model_name='teamb',
            old_name='or_sloc',
            new_name='or_loc',
        ),
    ]
