# Generated by Django 5.0.2 on 2024-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0019_rename_dr_sjn_teama_dr_jn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teama',
            name='game_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
