# Generated by Django 5.0.2 on 2024-05-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_teama_match_id_teamb_match_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamA',
        ),
        migrations.DeleteModel(
            name='TeamB',
        ),
    ]
