# Generated by Django 5.0.2 on 2024-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0023_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teama',
            name='dr_loc',
        ),
        migrations.RemoveField(
            model_name='teama',
            name='or_loc',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='dr_loc',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='or_loc',
        ),
        migrations.AddField(
            model_name='teama',
            name='jb_lose_jn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teama',
            name='jb_win_jn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='jb_lose_jn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamb',
            name='jb_win_jn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamb',
            name='game_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
