# Generated by Django 5.0.2 on 2024-05-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_remove_teama_match_id_remove_teamb_match_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamA',
        ),
        migrations.DeleteModel(
            name='TeamB',
        ),
    ]
