# Generated by Django 5.0.2 on 2024-05-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0008_matches_team_a_players_matches_team_b_players'),
        ('match', '0026_delete_teama_delete_teamb'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamA',
            fields=[
                ('match_time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('game_time', models.TimeField(blank=True, null=True)),
                ('start_game', models.CharField(blank=True, max_length=50, null=True)),
                ('end_game', models.CharField(blank=True, max_length=50, null=True)),
                ('quarter', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('shot', models.CharField(blank=True, max_length=50, null=True)),
                ('shot_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sjn', models.CharField(blank=True, max_length=50, null=True)),
                ('sloc', models.JSONField(blank=True, null=True)),
                ('djn', models.CharField(blank=True, max_length=50, null=True)),
                ('dloc', models.JSONField(blank=True, null=True)),
                ('jb_win_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('jb_lose_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('ajn', models.CharField(blank=True, max_length=50, null=True)),
                ('miss_type', models.CharField(blank=True, max_length=50, null=True)),
                ('foul_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('player_in_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('player_out_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('rft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='annotation.matches')),
            ],
        ),
        migrations.CreateModel(
            name='TeamB',
            fields=[
                ('match_time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('game_time', models.TimeField(blank=True, null=True)),
                ('start_game', models.CharField(blank=True, max_length=50, null=True)),
                ('end_game', models.CharField(blank=True, max_length=50, null=True)),
                ('quarter', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('shot', models.CharField(blank=True, max_length=50, null=True)),
                ('shot_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sjn', models.CharField(blank=True, max_length=50, null=True)),
                ('sloc', models.JSONField(blank=True, null=True)),
                ('djn', models.CharField(blank=True, max_length=50, null=True)),
                ('dloc', models.JSONField(blank=True, null=True)),
                ('jb_win_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('jb_lose_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('ajn', models.CharField(blank=True, max_length=50, null=True)),
                ('miss_type', models.CharField(blank=True, max_length=50, null=True)),
                ('foul_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('player_in_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('player_out_jn', models.CharField(blank=True, max_length=50, null=True)),
                ('rft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='annotation.matches')),
            ],
        ),
    ]
