# Generated by Django 5.0.2 on 2024-05-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0027_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teama',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='teamb',
            name='match_id',
        ),
    ]
